"""initial schema

Revision ID: e7d2de3acad1
Revises:
Create Date: 2026-05-20 17:06:41.761362

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7d2de3acad1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_category', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('nlp_keywords', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('collection_week', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_articles_collection_week', 'articles', ['collection_week'], unique=False)
    op.create_index('ix_articles_source_name', 'articles', ['source_name'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('articles_fetched', sa.Integer(), nullable=False),
    sa.Column('articles_new', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_week'), 'collection_runs', ['week'], unique=False)
    op.create_table('newsletter_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('articles_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_logs_week'), 'newsletter_logs', ['week'], unique=False)
    op.create_table('newsletter_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.String(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_picks_week'), 'newsletter_picks', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_picks_week'), table_name='newsletter_picks')
    op.drop_table('newsletter_picks')
    op.drop_index(op.f('ix_newsletter_logs_week'), table_name='newsletter_logs')
    op.drop_table('newsletter_logs')
    op.drop_index(op.f('ix_collection_runs_week'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index('ix_articles_source_name', table_name='articles')
    op.drop_index('ix_articles_collection_week', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
